<?php

namespace OkZhu\WebAdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

	public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM OkZhuWebAdminBundle:User u ORDER BY u.name ASC'
            )
            ->getResult();
    }
}
